### ISSUE TITLE
Implement Literal Strings

### ISSUE THREAD

**Issue by wesleywiser** [wesleywiser/toml-rust#5]
Literal strings are surrounded by single quotes. Like basic strings, they must appear on a single line:

``` toml
# What you see is what you get.
winpath  = 'C:\Users\nodejs\templates'
winpath2 = '\\ServerX\admin$\system32\'
quoted   = 'Tom "Dubs" Preston-Werner'
regex    = '<\i\c*\s*>'
```
